name: Tests using Bun
on: 
  push:
    branches:
    - development
  workflow_dispatch:

jobs:
   run_tests:
     name: Run tests
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: Setup Bun
       uses: oven-sh/setup-bun@v2
     - name: Install Dependencies
       run: bun install
     - name: Run test
       run: bun test
     
   

    
